---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  template:
    metadata:
      labels:
        app: myapp
    #    version: v2
        version: v3
    spec: 
      containers:
        - name: myapp-cont
  #        image: shaikkhajaibrahim/myapp:2.0
          image: shaikkhajaibrahim/myapp:3.0
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
